<?xml version="1.0" encoding="utf-8"?><Database Name="TrungTamNgoaiNguDB" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-3T163PO\SQLEXPRESS;Initial Catalog=TrungTamNgoaiNguDB;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="TrungTamNgoaiNguDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DIADDIEM" Member="DIADDIEMs">
    <Type Name="DIADDIEM">
      <Column Name="MADIADIEM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENDIADIEM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THISINH" Member="THISINHs">
    <Type Name="THISINH">
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KETQUA" Member="KETQUAs">
    <Type Name="KETQUA">
      <Column Name="SoBaoDanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoaThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemNghe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemNoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemDoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemViet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOATHI" Member="KHOATHIs">
    <Type Name="KHOATHI">
      <Column Name="MaKhoaThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenKhoaThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayThi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUDUTHI" Member="PHIEUDUTHIs">
    <Type Name="PHIEUDUTHI">
      <Column Name="TenPhongThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CaThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBaoDanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGTHI" Member="PHONGTHIs">
    <Type Name="PHONGTHI">
      <Column Name="TenPhongThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoaThi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>