#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TrungTamNgoaiNguDB")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDIADIEM(DIADIEM instance);
    partial void UpdateDIADIEM(DIADIEM instance);
    partial void DeleteDIADIEM(DIADIEM instance);
    partial void InsertTHISINH(THISINH instance);
    partial void UpdateTHISINH(THISINH instance);
    partial void DeleteTHISINH(THISINH instance);
    partial void InsertGIOITINH(GIOITINH instance);
    partial void UpdateGIOITINH(GIOITINH instance);
    partial void DeleteGIOITINH(GIOITINH instance);
    partial void InsertKETQUA(KETQUA instance);
    partial void UpdateKETQUA(KETQUA instance);
    partial void DeleteKETQUA(KETQUA instance);
    partial void InsertKHOATHI(KHOATHI instance);
    partial void UpdateKHOATHI(KHOATHI instance);
    partial void DeleteKHOATHI(KHOATHI instance);
    partial void InsertPHIEUDUTHI(PHIEUDUTHI instance);
    partial void UpdatePHIEUDUTHI(PHIEUDUTHI instance);
    partial void DeletePHIEUDUTHI(PHIEUDUTHI instance);
    partial void InsertPHONGTHI(PHONGTHI instance);
    partial void UpdatePHONGTHI(PHONGTHI instance);
    partial void DeletePHONGTHI(PHONGTHI instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Backend.Properties.Settings.Default.TrungTamNgoaiNguDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DIADIEM> DIADIEMs
		{
			get
			{
				return this.GetTable<DIADIEM>();
			}
		}
		
		public System.Data.Linq.Table<THISINH> THISINHs
		{
			get
			{
				return this.GetTable<THISINH>();
			}
		}
		
		public System.Data.Linq.Table<GIOITINH> GIOITINHs
		{
			get
			{
				return this.GetTable<GIOITINH>();
			}
		}
		
		public System.Data.Linq.Table<KETQUA> KETQUAs
		{
			get
			{
				return this.GetTable<KETQUA>();
			}
		}
		
		public System.Data.Linq.Table<KHOATHI> KHOATHIs
		{
			get
			{
				return this.GetTable<KHOATHI>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDUTHI> PHIEUDUTHIs
		{
			get
			{
				return this.GetTable<PHIEUDUTHI>();
			}
		}
		
		public System.Data.Linq.Table<PHONGTHI> PHONGTHIs
		{
			get
			{
				return this.GetTable<PHONGTHI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADIEM")]
	public partial class DIADIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADIADIEM;
		
		private string _TENDIADIEM;
		
		private EntitySet<THISINH> _THISINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADIADIEMChanging(string value);
    partial void OnMADIADIEMChanged();
    partial void OnTENDIADIEMChanging(string value);
    partial void OnTENDIADIEMChanged();
    #endregion
		
		public DIADIEM()
		{
			this._THISINHs = new EntitySet<THISINH>(new Action<THISINH>(this.attach_THISINHs), new Action<THISINH>(this.detach_THISINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADIADIEM", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADIADIEM
		{
			get
			{
				return this._MADIADIEM;
			}
			set
			{
				if ((this._MADIADIEM != value))
				{
					this.OnMADIADIEMChanging(value);
					this.SendPropertyChanging();
					this._MADIADIEM = value;
					this.SendPropertyChanged("MADIADIEM");
					this.OnMADIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDIADIEM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENDIADIEM
		{
			get
			{
				return this._TENDIADIEM;
			}
			set
			{
				if ((this._TENDIADIEM != value))
				{
					this.OnTENDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._TENDIADIEM = value;
					this.SendPropertyChanged("TENDIADIEM");
					this.OnTENDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_THISINH", Storage="_THISINHs", ThisKey="MADIADIEM", OtherKey="NoiSinh")]
		public EntitySet<THISINH> THISINHs
		{
			get
			{
				return this._THISINHs;
			}
			set
			{
				this._THISINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THISINHs(THISINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}
		
		private void detach_THISINHs(THISINH entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THISINH")]
	public partial class THISINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CMND;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _NoiSinh;
		
		private int _SDT;
		
		private EntitySet<PHIEUDUTHI> _PHIEUDUTHIs;
		
		private EntityRef<DIADIEM> _DIADIEM;
		
		private EntityRef<GIOITINH> _GIOITINH1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    #endregion
		
		public THISINH()
		{
			this._PHIEUDUTHIs = new EntitySet<PHIEUDUTHI>(new Action<PHIEUDUTHI>(this.attach_PHIEUDUTHIs), new Action<PHIEUDUTHI>(this.detach_PHIEUDUTHIs));
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._GIOITINH1 = default(EntityRef<GIOITINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					if (this._GIOITINH1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					if (this._DIADIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THISINH_PHIEUDUTHI", Storage="_PHIEUDUTHIs", ThisKey="CMND", OtherKey="CMND")]
		public EntitySet<PHIEUDUTHI> PHIEUDUTHIs
		{
			get
			{
				return this._PHIEUDUTHIs;
			}
			set
			{
				this._PHIEUDUTHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_THISINH", Storage="_DIADIEM", ThisKey="NoiSinh", OtherKey="MADIADIEM", IsForeignKey=true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.THISINHs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.THISINHs.Add(this);
						this._NoiSinh = value.MADIADIEM;
					}
					else
					{
						this._NoiSinh = default(string);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOITINH_THISINH", Storage="_GIOITINH1", ThisKey="GioiTinh", OtherKey="GIOITINH1", IsForeignKey=true)]
		public GIOITINH GIOITINH1
		{
			get
			{
				return this._GIOITINH1.Entity;
			}
			set
			{
				GIOITINH previousValue = this._GIOITINH1.Entity;
				if (((previousValue != value) 
							|| (this._GIOITINH1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIOITINH1.Entity = null;
						previousValue.THISINHs.Remove(this);
					}
					this._GIOITINH1.Entity = value;
					if ((value != null))
					{
						value.THISINHs.Add(this);
						this._GioiTinh = value.GIOITINH1;
					}
					else
					{
						this._GioiTinh = default(string);
					}
					this.SendPropertyChanged("GIOITINH1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.THISINH = this;
		}
		
		private void detach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.THISINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIOITINH")]
	public partial class GIOITINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GIOITINH1;
		
		private EntitySet<THISINH> _THISINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGIOITINH1Changing(string value);
    partial void OnGIOITINH1Changed();
    #endregion
		
		public GIOITINH()
		{
			this._THISINHs = new EntitySet<THISINH>(new Action<THISINH>(this.attach_THISINHs), new Action<THISINH>(this.detach_THISINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="GIOITINH", Storage="_GIOITINH1", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GIOITINH1
		{
			get
			{
				return this._GIOITINH1;
			}
			set
			{
				if ((this._GIOITINH1 != value))
				{
					this.OnGIOITINH1Changing(value);
					this.SendPropertyChanging();
					this._GIOITINH1 = value;
					this.SendPropertyChanged("GIOITINH1");
					this.OnGIOITINH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOITINH_THISINH", Storage="_THISINHs", ThisKey="GIOITINH1", OtherKey="GioiTinh")]
		public EntitySet<THISINH> THISINHs
		{
			get
			{
				return this._THISINHs;
			}
			set
			{
				this._THISINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THISINHs(THISINH entity)
		{
			this.SendPropertyChanging();
			entity.GIOITINH1 = this;
		}
		
		private void detach_THISINHs(THISINH entity)
		{
			this.SendPropertyChanging();
			entity.GIOITINH1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KETQUA")]
	public partial class KETQUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoBaoDanh;
		
		private string _MaKhoaThi;
		
		private int _DiemNghe;
		
		private int _DiemNoi;
		
		private int _DiemDoc;
		
		private int _DiemViet;
		
		private EntityRef<KHOATHI> _KHOATHI;
		
		private EntityRef<PHIEUDUTHI> _PHIEUDUTHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoBaoDanhChanging(string value);
    partial void OnSoBaoDanhChanged();
    partial void OnMaKhoaThiChanging(string value);
    partial void OnMaKhoaThiChanged();
    partial void OnDiemNgheChanging(int value);
    partial void OnDiemNgheChanged();
    partial void OnDiemNoiChanging(int value);
    partial void OnDiemNoiChanged();
    partial void OnDiemDocChanging(int value);
    partial void OnDiemDocChanged();
    partial void OnDiemVietChanging(int value);
    partial void OnDiemVietChanged();
    #endregion
		
		public KETQUA()
		{
			this._KHOATHI = default(EntityRef<KHOATHI>);
			this._PHIEUDUTHI = default(EntityRef<PHIEUDUTHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBaoDanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoBaoDanh
		{
			get
			{
				return this._SoBaoDanh;
			}
			set
			{
				if ((this._SoBaoDanh != value))
				{
					if (this._PHIEUDUTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoBaoDanhChanging(value);
					this.SendPropertyChanging();
					this._SoBaoDanh = value;
					this.SendPropertyChanged("SoBaoDanh");
					this.OnSoBaoDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoaThi
		{
			get
			{
				return this._MaKhoaThi;
			}
			set
			{
				if ((this._MaKhoaThi != value))
				{
					if (this._KHOATHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaThi = value;
					this.SendPropertyChanged("MaKhoaThi");
					this.OnMaKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemNghe", DbType="Int NOT NULL")]
		public int DiemNghe
		{
			get
			{
				return this._DiemNghe;
			}
			set
			{
				if ((this._DiemNghe != value))
				{
					this.OnDiemNgheChanging(value);
					this.SendPropertyChanging();
					this._DiemNghe = value;
					this.SendPropertyChanged("DiemNghe");
					this.OnDiemNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemNoi", DbType="Int NOT NULL")]
		public int DiemNoi
		{
			get
			{
				return this._DiemNoi;
			}
			set
			{
				if ((this._DiemNoi != value))
				{
					this.OnDiemNoiChanging(value);
					this.SendPropertyChanging();
					this._DiemNoi = value;
					this.SendPropertyChanged("DiemNoi");
					this.OnDiemNoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDoc", DbType="Int NOT NULL")]
		public int DiemDoc
		{
			get
			{
				return this._DiemDoc;
			}
			set
			{
				if ((this._DiemDoc != value))
				{
					this.OnDiemDocChanging(value);
					this.SendPropertyChanging();
					this._DiemDoc = value;
					this.SendPropertyChanged("DiemDoc");
					this.OnDiemDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemViet", DbType="Int NOT NULL")]
		public int DiemViet
		{
			get
			{
				return this._DiemViet;
			}
			set
			{
				if ((this._DiemViet != value))
				{
					this.OnDiemVietChanging(value);
					this.SendPropertyChanging();
					this._DiemViet = value;
					this.SendPropertyChanged("DiemViet");
					this.OnDiemVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_KETQUA", Storage="_KHOATHI", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi", IsForeignKey=true)]
		public KHOATHI KHOATHI
		{
			get
			{
				return this._KHOATHI.Entity;
			}
			set
			{
				KHOATHI previousValue = this._KHOATHI.Entity;
				if (((previousValue != value) 
							|| (this._KHOATHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOATHI.Entity = null;
						previousValue.KETQUAs.Remove(this);
					}
					this._KHOATHI.Entity = value;
					if ((value != null))
					{
						value.KETQUAs.Add(this);
						this._MaKhoaThi = value.MaKhoaThi;
					}
					else
					{
						this._MaKhoaThi = default(string);
					}
					this.SendPropertyChanged("KHOATHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDUTHI_KETQUA", Storage="_PHIEUDUTHI", ThisKey="SoBaoDanh", OtherKey="SoBaoDanh", IsForeignKey=true)]
		public PHIEUDUTHI PHIEUDUTHI
		{
			get
			{
				return this._PHIEUDUTHI.Entity;
			}
			set
			{
				PHIEUDUTHI previousValue = this._PHIEUDUTHI.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDUTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDUTHI.Entity = null;
						previousValue.KETQUAs.Remove(this);
					}
					this._PHIEUDUTHI.Entity = value;
					if ((value != null))
					{
						value.KETQUAs.Add(this);
						this._SoBaoDanh = value.SoBaoDanh;
					}
					else
					{
						this._SoBaoDanh = default(string);
					}
					this.SendPropertyChanged("PHIEUDUTHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOATHI")]
	public partial class KHOATHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoaThi;
		
		private string _TenKhoaThi;
		
		private string _TrinhDo;
		
		private System.DateTime _NgayThi;
		
		private EntitySet<KETQUA> _KETQUAs;
		
		private EntitySet<PHIEUDUTHI> _PHIEUDUTHIs;
		
		private EntitySet<PHONGTHI> _PHONGTHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaThiChanging(string value);
    partial void OnMaKhoaThiChanged();
    partial void OnTenKhoaThiChanging(string value);
    partial void OnTenKhoaThiChanged();
    partial void OnTrinhDoChanging(string value);
    partial void OnTrinhDoChanged();
    partial void OnNgayThiChanging(System.DateTime value);
    partial void OnNgayThiChanged();
    #endregion
		
		public KHOATHI()
		{
			this._KETQUAs = new EntitySet<KETQUA>(new Action<KETQUA>(this.attach_KETQUAs), new Action<KETQUA>(this.detach_KETQUAs));
			this._PHIEUDUTHIs = new EntitySet<PHIEUDUTHI>(new Action<PHIEUDUTHI>(this.attach_PHIEUDUTHIs), new Action<PHIEUDUTHI>(this.detach_PHIEUDUTHIs));
			this._PHONGTHIs = new EntitySet<PHONGTHI>(new Action<PHONGTHI>(this.attach_PHONGTHIs), new Action<PHONGTHI>(this.detach_PHONGTHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoaThi
		{
			get
			{
				return this._MaKhoaThi;
			}
			set
			{
				if ((this._MaKhoaThi != value))
				{
					this.OnMaKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaThi = value;
					this.SendPropertyChanged("MaKhoaThi");
					this.OnMaKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhoaThi
		{
			get
			{
				return this._TenKhoaThi;
			}
			set
			{
				if ((this._TenKhoaThi != value))
				{
					this.OnTenKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoaThi = value;
					this.SendPropertyChanged("TenKhoaThi");
					this.OnTenKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="DateTime NOT NULL")]
		public System.DateTime NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_KETQUA", Storage="_KETQUAs", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi")]
		public EntitySet<KETQUA> KETQUAs
		{
			get
			{
				return this._KETQUAs;
			}
			set
			{
				this._KETQUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_PHIEUDUTHI", Storage="_PHIEUDUTHIs", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi")]
		public EntitySet<PHIEUDUTHI> PHIEUDUTHIs
		{
			get
			{
				return this._PHIEUDUTHIs;
			}
			set
			{
				this._PHIEUDUTHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_PHONGTHI", Storage="_PHONGTHIs", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi")]
		public EntitySet<PHONGTHI> PHONGTHIs
		{
			get
			{
				return this._PHONGTHIs;
			}
			set
			{
				this._PHONGTHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KETQUAs(KETQUA entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = this;
		}
		
		private void detach_KETQUAs(KETQUA entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = null;
		}
		
		private void attach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = this;
		}
		
		private void detach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = null;
		}
		
		private void attach_PHONGTHIs(PHONGTHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = this;
		}
		
		private void detach_PHONGTHIs(PHONGTHI entity)
		{
			this.SendPropertyChanging();
			entity.KHOATHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDUTHI")]
	public partial class PHIEUDUTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoBaoDanh;
		
		private string _TenPhongThi;
		
		private string _CMND;
		
		private string _CaThi;
		
		private string _MaKhoaThi;
		
		private EntitySet<KETQUA> _KETQUAs;
		
		private EntityRef<THISINH> _THISINH;
		
		private EntityRef<KHOATHI> _KHOATHI;
		
		private EntityRef<PHONGTHI> _PHONGTHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoBaoDanhChanging(string value);
    partial void OnSoBaoDanhChanged();
    partial void OnTenPhongThiChanging(string value);
    partial void OnTenPhongThiChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnCaThiChanging(string value);
    partial void OnCaThiChanged();
    partial void OnMaKhoaThiChanging(string value);
    partial void OnMaKhoaThiChanged();
    #endregion
		
		public PHIEUDUTHI()
		{
			this._KETQUAs = new EntitySet<KETQUA>(new Action<KETQUA>(this.attach_KETQUAs), new Action<KETQUA>(this.detach_KETQUAs));
			this._THISINH = default(EntityRef<THISINH>);
			this._KHOATHI = default(EntityRef<KHOATHI>);
			this._PHONGTHI = default(EntityRef<PHONGTHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBaoDanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoBaoDanh
		{
			get
			{
				return this._SoBaoDanh;
			}
			set
			{
				if ((this._SoBaoDanh != value))
				{
					this.OnSoBaoDanhChanging(value);
					this.SendPropertyChanging();
					this._SoBaoDanh = value;
					this.SendPropertyChanged("SoBaoDanh");
					this.OnSoBaoDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPhongThi
		{
			get
			{
				return this._TenPhongThi;
			}
			set
			{
				if ((this._TenPhongThi != value))
				{
					if (this._PHONGTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenPhongThiChanging(value);
					this.SendPropertyChanging();
					this._TenPhongThi = value;
					this.SendPropertyChanged("TenPhongThi");
					this.OnTenPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					if (this._THISINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CaThi
		{
			get
			{
				return this._CaThi;
			}
			set
			{
				if ((this._CaThi != value))
				{
					this.OnCaThiChanging(value);
					this.SendPropertyChanging();
					this._CaThi = value;
					this.SendPropertyChanged("CaThi");
					this.OnCaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaKhoaThi
		{
			get
			{
				return this._MaKhoaThi;
			}
			set
			{
				if ((this._MaKhoaThi != value))
				{
					if (this._KHOATHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaThi = value;
					this.SendPropertyChanged("MaKhoaThi");
					this.OnMaKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDUTHI_KETQUA", Storage="_KETQUAs", ThisKey="SoBaoDanh", OtherKey="SoBaoDanh")]
		public EntitySet<KETQUA> KETQUAs
		{
			get
			{
				return this._KETQUAs;
			}
			set
			{
				this._KETQUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THISINH_PHIEUDUTHI", Storage="_THISINH", ThisKey="CMND", OtherKey="CMND", IsForeignKey=true)]
		public THISINH THISINH
		{
			get
			{
				return this._THISINH.Entity;
			}
			set
			{
				THISINH previousValue = this._THISINH.Entity;
				if (((previousValue != value) 
							|| (this._THISINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THISINH.Entity = null;
						previousValue.PHIEUDUTHIs.Remove(this);
					}
					this._THISINH.Entity = value;
					if ((value != null))
					{
						value.PHIEUDUTHIs.Add(this);
						this._CMND = value.CMND;
					}
					else
					{
						this._CMND = default(string);
					}
					this.SendPropertyChanged("THISINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_PHIEUDUTHI", Storage="_KHOATHI", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi", IsForeignKey=true)]
		public KHOATHI KHOATHI
		{
			get
			{
				return this._KHOATHI.Entity;
			}
			set
			{
				KHOATHI previousValue = this._KHOATHI.Entity;
				if (((previousValue != value) 
							|| (this._KHOATHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOATHI.Entity = null;
						previousValue.PHIEUDUTHIs.Remove(this);
					}
					this._KHOATHI.Entity = value;
					if ((value != null))
					{
						value.PHIEUDUTHIs.Add(this);
						this._MaKhoaThi = value.MaKhoaThi;
					}
					else
					{
						this._MaKhoaThi = default(string);
					}
					this.SendPropertyChanged("KHOATHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTHI_PHIEUDUTHI", Storage="_PHONGTHI", ThisKey="TenPhongThi", OtherKey="TenPhongThi", IsForeignKey=true)]
		public PHONGTHI PHONGTHI
		{
			get
			{
				return this._PHONGTHI.Entity;
			}
			set
			{
				PHONGTHI previousValue = this._PHONGTHI.Entity;
				if (((previousValue != value) 
							|| (this._PHONGTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGTHI.Entity = null;
						previousValue.PHIEUDUTHIs.Remove(this);
					}
					this._PHONGTHI.Entity = value;
					if ((value != null))
					{
						value.PHIEUDUTHIs.Add(this);
						this._TenPhongThi = value.TenPhongThi;
					}
					else
					{
						this._TenPhongThi = default(string);
					}
					this.SendPropertyChanged("PHONGTHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KETQUAs(KETQUA entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDUTHI = this;
		}
		
		private void detach_KETQUAs(KETQUA entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDUTHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGTHI")]
	public partial class PHONGTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenPhongThi;
		
		private string _MaKhoaThi;
		
		private int _SoLuong;
		
		private EntitySet<PHIEUDUTHI> _PHIEUDUTHIs;
		
		private EntityRef<KHOATHI> _KHOATHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenPhongThiChanging(string value);
    partial void OnTenPhongThiChanged();
    partial void OnMaKhoaThiChanging(string value);
    partial void OnMaKhoaThiChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public PHONGTHI()
		{
			this._PHIEUDUTHIs = new EntitySet<PHIEUDUTHI>(new Action<PHIEUDUTHI>(this.attach_PHIEUDUTHIs), new Action<PHIEUDUTHI>(this.detach_PHIEUDUTHIs));
			this._KHOATHI = default(EntityRef<KHOATHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenPhongThi
		{
			get
			{
				return this._TenPhongThi;
			}
			set
			{
				if ((this._TenPhongThi != value))
				{
					this.OnTenPhongThiChanging(value);
					this.SendPropertyChanging();
					this._TenPhongThi = value;
					this.SendPropertyChanged("TenPhongThi");
					this.OnTenPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaThi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaKhoaThi
		{
			get
			{
				return this._MaKhoaThi;
			}
			set
			{
				if ((this._MaKhoaThi != value))
				{
					if (this._KHOATHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaThi = value;
					this.SendPropertyChanged("MaKhoaThi");
					this.OnMaKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTHI_PHIEUDUTHI", Storage="_PHIEUDUTHIs", ThisKey="TenPhongThi", OtherKey="TenPhongThi")]
		public EntitySet<PHIEUDUTHI> PHIEUDUTHIs
		{
			get
			{
				return this._PHIEUDUTHIs;
			}
			set
			{
				this._PHIEUDUTHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOATHI_PHONGTHI", Storage="_KHOATHI", ThisKey="MaKhoaThi", OtherKey="MaKhoaThi", IsForeignKey=true)]
		public KHOATHI KHOATHI
		{
			get
			{
				return this._KHOATHI.Entity;
			}
			set
			{
				KHOATHI previousValue = this._KHOATHI.Entity;
				if (((previousValue != value) 
							|| (this._KHOATHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOATHI.Entity = null;
						previousValue.PHONGTHIs.Remove(this);
					}
					this._KHOATHI.Entity = value;
					if ((value != null))
					{
						value.PHONGTHIs.Add(this);
						this._MaKhoaThi = value.MaKhoaThi;
					}
					else
					{
						this._MaKhoaThi = default(string);
					}
					this.SendPropertyChanged("KHOATHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTHI = this;
		}
		
		private void detach_PHIEUDUTHIs(PHIEUDUTHI entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTHI = null;
		}
	}
}
#pragma warning restore 1591
